# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a9b4ca67ddd3df64fbd4d74b3a23bf6916f35e3029714bf112529b2e433af9c668b3bbb62f028f40fb07fc409e9f1c74f63f6bd32ceeac7cc1a338db071a92

test:
  secret_key_base: 44e861758032030d111e3c9813c6a513249095907044355759aaf9c14d3d300048756eb679058fcbd6901a791ed6b1f2134253febd5383673b55888782e671a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
